### ISSUE TITLE
404 when clicking on direct test result link

### ISSUE THREAD

**Issue by michalvanco** [zeroturnaround/build-flow-test-aggregator#13]
In flow, when you have some failures present and you are willing to see the output of error, you get a 404 because the target link is invalid.

Example:
Test failure points to:
https://ci.xxx.com/job/my-flow-job/104/testReport/junit/com.package/class/test/, but the valid URL should be
https://ci.xxx.com/job/specific-job-triggered-from-flow/472/testReport/package/class/test/

The workaround is to click on Test Result link (https://ci.xxx.com/job/my-flow-job/104/testReport) from which you can access the subsequent links properly.

Can you please consider the update of this / junit plugin so that it properly handles these links? Thanks!

**Comment by michalvanco** [comment]
Hi @poolik, I can see you have merged few new changes - do you plan to release a new plugin version now?

Thanks!

**Comment by poolik** [comment]
Hi @michalvanco! 
Sure, I'm planning on doing the release today evening after I've tested the changes a bit more.

**Comment by michalvanco** [comment]
Cool, thanks!
