### ISSUE TITLE
Problem with aggregation of junit report generated by Robot Framework

### ISSUE THREAD

**Issue by winko** [zeroturnaround/build-flow-test-aggregator#5]
Hi!

consider following scenario:
* job airwbeUiTesting_DuringTheDay_Methusalix_develop
  * generates following junit report as file "robot_output/xUnitCompatibleResultFile.xml":
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite failures="0" tests="2" errors="0" name="Testsuites" skip="0">
<testcase classname="Testsuites.airwbe Einzelreservierung WBS-bel" name="1 Zimmer - testserver" time="127">
</testcase>
<testcase classname="Testsuites.airwbe Einzelreservierung WBS-nfw" name="1 Zimmer - testserver" time="122">
</testcase>
</testsuite>
```
  * is configured with:
    * Publish JUnit test result report > Test report XMLs: robot_output/xUnitCompatibleResultFile.xml

* job aggregate
  * is configured with:
    * Define build flow using flow DSL	: 
```groovy
build ( "baoServerBuildAndDeploy_Methusalix_develop" )
build ( "airwbeUiTesting_DuringTheDay_Methusalix_develop" )
```
    * Aggregate build flow test results
  * after a build the Aggregated Test Results page looks like that:
![aggregatedtestresults_problematic](https://cloud.githubusercontent.com/assets/3777646/6059095/151eafba-ad2e-11e4-9db8-8b00b2aa0ec1.png)
  * when I click on the airwbeUiTesting_DuringTheDay_Methusalix_develop link the Test Result page looks like that:
![testresults_airwbe_ok](https://cloud.githubusercontent.com/assets/3777646/6059191/fe077144-ad2e-11e4-95df-54efa1d78d5c.png)

So there are following problems:
* on the Aggregated Test Results page:
  * no Duration, All, Failed, Skipped data for the airwbeUiTesting_DuringTheDay_Methusalix_develop  test results
  * airwbeUiTesting_DuringTheDay_Methusalix_develop  test results appears below "Failed Tests" although there are no failed tests

Regards!

**Comment by poolik** [comment]
Hi winko!

Thanks for your input. Is the airwbeUiTesting_DuringTheDay_Methusalix_develop job a matrix job or could you tell me a little about the job configuration. The 1.0 release has some known limitations with regards to some job types. Personally I only needed it to aggregate results of free-style software projects. Other job types probably require a little more integration.

**Comment by winko** [comment]
Hi poolik!

airwbeUiTesting_DuringTheDay_Methusalix_develop job is a normal free-style job. The special feature of the job is that it uses Robot Framework (pybot with the argument  --xunit) for the generation of the junit report. And there is also the section "Publish robot framework test results" activated within the job.

**Comment by poolik** [comment]
Hi winko!

Sorry for the late reply, but could you send me the output of "airwbeUiTesting_DuringTheDay_Methusalix_develop" job's junitResult.xml, it should be /JENKINS_DIR/jobs/airwbeUiTesting_DuringTheDay_Methusalix_develop/builds/BUILD_NR directory.

For a simple test job that I have set up it's has the following content:
http://cl.ly/code/3a1N1c2X2o1z

**Comment by winko** [comment]
You are welcome!

```xml
<?xml version='1.0' encoding='UTF-8'?>
<result plugin="junit@1.4">
  <suites>
    <suite>
      <file>D:\jenkinsRoot\workspace\airwbeUiTesting_DuringTheDay_Methusalix_develop\robot_output\xUnitCompatibleResultFile.xml</file
>
      <name>Testsuites</name>
      <duration>233.0</duration>
      <cases>
        <case>
          <duration>128.0</duration>
          <className>Testsuites.airwbe Einzelreservierung WBS-bel</className>
          <testName>1 Zimmer - testserver</testName>
          <skipped>false</skipped>
          <failedSince>0</failedSince>
        </case>
        <case>
          <duration>105.0</duration>
          <className>Testsuites.airwbe Einzelreservierung WBS-nfw</className>
          <testName>1 Zimmer - testserver</testName>
          <skipped>false</skipped>
          <failedSince>0</failedSince>
        </case>
      </cases>
    </suite>
  </suites>
  <duration>233.0</duration>
  <keepLongStdio>false</keepLongStdio>
</result>
```

**Comment by poolik** [comment]
Hi @winko !

I think I finally figured out what's going on. You should configure normal "Publish JUnit test result report" for the job if your generating junit reports anyway. I believe currently you're using this "Robot Framework Plugin" for publishing the test result, but looking at the source code of that plugin I see that they are defining some child classes of AbstractTestResultAction on their own (https://github.com/jenkinsci/robot-plugin). 

If you start using the normal "Publish JUnit test result report", the problem should go away.
