### ISSUE TITLE
Question: Aggregation for nested build flow jobs

### ISSUE THREAD

**Issue by winko** [zeroturnaround/build-flow-test-aggregator#6]
Hi!
Is it possible to aggregate test results for following build flow job "job1":
```groovy
        build("job1A")
        build("job1B")
        build("job1C")
```
where "job1[A-C]" are build flow jobs which build testing jobs. Thus we have a cascading structure like this:

* Build flow job "job1" builds
  * Build flow job "job1A" builds
    * Testing job which generates test results

???

**Comment by poolik** [comment]
This could be achieved I just need to change the action i retrieve from build from TestResultAction to AbstractTestResultAction. I'll look into it among other improvements and see if I can release 1.1

**Comment by winko** [comment]
Great!

**Comment by michalvanco** [comment]
Hi, I had a pretty much the same issue and I've just send a proposal at https://github.com/zeroturnaround/build-flow-test-aggregator/pull/10 - can you please have a look?

There are two possible options:
1) what @poolik says has a prerequisites that triggered jobs have to aggregate the results as well (btw. there is a different structure of test results on flow job)
2) iterate over all jobs which were triggered directly or from the other flow jobs - this is what I did at my PR, with this option I would like to extend another option to aggregate the results from multijob - what do you think? 
Thanks in advance for a feedback!

**Comment by winko** [comment]
The recursive solution 2) looks nice. What I have to do to test it on my Jenkins instance?

**Comment by michalvanco** [comment]
Hi @winko, 
you can checkout my branch, run `mvn package` and install the plugin manually at your Jenkins instance using the `*.hpi` file. Or you can have a look at the hpi maven plugin which would do all the job as well (https://jenkins-ci.org/maven-hpi-plugin/).
Best regards, Michal

**Comment by michalvanco** [comment]
Updated and extended code for aggregating results from the flow and multijob builds prepared at https://github.com/zeroturnaround/build-flow-test-aggregator/pull/11

**Comment by poolik** [comment]
I've released version 1.1 of the plugin, should be visible from Jenkins in about 6h the latest. Thanks everyone for contributing!

**Comment by sathismr** [comment]
Can we use this plugin for TestNG results aggregation? It works fine with JUnit... somehow, I am missing something in configuring TestNG reports.

**Comment by michalvanco** [comment]
Hi @sathismr, TestNG produce test results in standard junit format so the answer is yes. You can need to archive the JUnit results inside jobs which you trigger from flow build and it will be properly aggregated.

**Comment by jgtaing** [comment]
Is the aggregated test report stored in the workspace anywhere? We are trying to have a script that will pull these aggregated reports from multiple Jenkins masters.

**Comment by poolik** [comment]
Hi @jgtaing the test reports aren't on disk the same way as JUnit xml results. But Jenkins does keep all of it's configurations and build metadata etc on disk as xml files. So if you look at the job folder with build flow aggregator (say $JENKINS_HOME/jobs/my-flow) then the aggregated results will be in each build.xml file (as in $JENKINS_HOME/jobs/my-flow/builds/X/build.xml). Look for the element <org.zeroturnaround.jenkins.flowbuildtestaggregator.FlowTestResults>. Unfortunately that will only point you to the aggregated build (project + build #).

But perhaps a simpler way is to query the data via Jenkins XML or JSON api. Just append "/api/json?depth=2" to the Jenkins flow build URL and it will output all of the data at once.
