### ISSUE TITLE
Display Build Name instead of Job name (or in addition) for test results

### ISSUE THREAD

**Issue by astraw38** [zeroturnaround/build-flow-test-aggregator#7]
When you have a build flow that has parametrized jobs, the test results become rather confusing, as it'll show the identical job name with no differentiation between the two builds (as seen in this comment: https://wiki.jenkins-ci.org/display/JENKINS/Build+Flow+Test+Aggregator+Plugin?focusedCommentId=75891296#comment-75891296)

It'd be really nice to have it include the build name or at least the parameters for the job.

**Comment by z41** [comment]
Also vote for this feature, would be really great to have this!
